#!/usr/bin/env bash
# Displays "To infinity and beyond" unless terminated
#+ displays "I am invincible!!!"
trap "echo 'I am invincible!!!'" 15
while true
do
	echo "To infinity and beyond"
	sleep 2
done
