#!/usr/bin/env bash
# Prints "Best School" ten times using a while loop
#+ prints "bad luck" on the 4th iteration and
#+ prints "good luck" on the 8th iteration
i=1
while [ $i -lt 11 ]
do
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
