#!/usr/bin/env bash
# Prints "Best School" ten times using a while loop
#+ prints "bad luck" on the 4th iteration and
#+ prints "good luck" on the 8th iteration
i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	(( ++i ))
done
