#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes
i=0
j=1
echo "Hour: $i"
i=$j
while [ $i -lt 60 ]
do
	echo "$i"
	(( ++i ))
done
echo "Hour: $j"
while [ $j -lt 13 ]
do
	echo "$j"
	(( ++j ))
done
